disabled_rules:
 - trailing_whitespace
 - identifier_name
 - line_length
 - cyclomatic_complexity
 - function_body_length
 - type_body_length
 - file_length
 - unused_closure_parameter

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
